bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'

urlpatterns = [
    path('process_payment/', views.bank_transaction_view, name='process_payment'),
    path('verify_transaction/<str:transaction_id>/', views.check_last_ok, name='verify_transaction'),
    path('last-ok/', views.get_last_ok, name='last_ok'),

]

bank_gateway2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls', namespace='market')),
    path('gateway/', include('gateway.urls', namespace='gateway')),
    path('bank/', include('bank.urls', namespace='bank')),

]

market/urls.py
from django.urls import path
from . import views


app_name = 'market'


urlpatterns = [
    path('cart/', views.cart_view, name='cart_view'),
    path('go-gateway/', views.go_to_gateway, name='go_gateway'),
    # path('checkout/', views.checkout_view, name='checkout_view'),
    path('failure/', views.failure_page, name='failure_page'),
    path('success/', views.success_page, name='success_page'),
    path('vrify-trancaction/', views.verify_transaction, name='verify_transaction'),
    path('psp-message/', views.psp_message, name='psp_message'),

]

market/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Market(models.Model):
    name = models.CharField(max_length=250)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name='owner_market')
    account_number = models.CharField(max_length=16, unique=True)


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_user')
    product_name = models.CharField(max_length=250)
    product_price = models.DecimalField(max_digits=20, decimal_places=1)
    quantity = models.IntegerField(default=1)
    total_price_cart = models.DecimalField(max_digits=20, decimal_places=1, blank=True, null=True)

    def total_price(self):
        return self.product_price * self.quantity


class Transaction(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transaction_user')
    account_number = models.CharField(max_length=16, unique=True)
    amount = models.DecimalField(max_digits=20, decimal_places=1)
    status = models.CharField(max_length=10)
    transaction_id = models.CharField(max_length=100, unique=True)
    create_time = models.DateTimeField()

    reference_id = models.DecimalField(max_digits=10, unique=True, decimal_places=0)
    last_market_ok = models.BooleanField(default=False)

    def __str__(self):
        return f"Transaction {self.transaction_id} - {self.status}"

market/forms.py
from django import forms


class AddToCartForm(forms.Form):
    product_name = forms.CharField(max_length=250)
    product_price = forms.CharField(max_length=20)
    quantity = forms.IntegerField(min_value=1, initial=1)

market/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from .models import CartItem, Transaction
from .forms import AddToCartForm
from .serializers import CartItemSerializer
from django.http import JsonResponse
import requests


# Create your views here.


def cart_view(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.total_price() for item in cart_items)

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            CartItem.objects.get_or_create(
                user=request.user,
                product_name=form.cleaned_data['product_name'],
                product_price=form.cleaned_data['product_price'],
                quantity=form.cleaned_data['quantity'],
                total_price_cart=total_price
            )
            return redirect('market:cart_view')
    else:
        form = AddToCartForm()

    context = {
        'form': form,
        'cart_items': cart_items,
        'total_price': total_price
    }

    return render(request, 'market/cart.html', context)


def go_to_gateway(request):
    cart_data = CartItem.objects.filter(user=request.user)
    if not cart_data.exists():
        return JsonResponse({'error': 'Cart is empty'}, status=400)

    # serializer = CartItemSerializer(cart_data, many=True)
    # data = serializer.data

    total_price = float(sum(item.total_price() for item in cart_data))
    product_name = 'Market A'  # فعلا اسم مارکت رو میفرستم چون تعداد زیادی اسم محصول ارسال میشد

    data = {
        'total_price': total_price,
        'product_name': product_name,
    }

    csrf_token = request.COOKIES.get('csrftoken')

    headers = {
        'X-CSRFToken': csrf_token
    }

    response = requests.post('http://127.0.0.1:8000/gateway/payment/', json=data, headers=headers)

    if response.status_code == 200:
        return redirect('http://127.0.0.1:8000/gateway/process-payment/')

    else:
        return JsonResponse({'error': 'Failed to send data to gateway'}, status=500)


def success_page(request):
    if request.method == 'POST':

        data = json.loads(request.body.decode('utf-8'))
        transaction_id = data.get('transaction_id')

        transaction = Transaction.objects.create(
            user=data.get('user'),
            transaction_id=data.get('transaction_id'),
            transaction_result=data.get('transaction_result'),
            reference_id=data.get('reference_id'),
            account_number=data.get('account_number'),
            amount=data.get('amount'),
            status=data.get('status'),
        )

        if data.get('status') == 'success' and verify_transaction(transaction_id):
            send_last_ok(transaction_id)

        return render(request, 'market/success_page.html')
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)


def verify_transaction(transaction_id):
    # get bank result
    # check product
    # send last oky for psp and bank
    return True


def send_last_ok(transaction_id):
    transaction = Transaction.objects.get(transaction_id=transaction_id)
    transaction.last_market_ok = True
    transaction.save()

    try:
        response = requests.post('http://psp-server/get-ok', json={
            'last_market_ok': True,
            'transaction_id': transaction_id
        })
        if response.status_code != 200:
            raise ValueError('Failed to notify psp')
    except requests.exceptions.RequestException as e:
        print(f'Error sending request to psp : {e}')


def failure_page(request):
    return render(request, 'market/failure_page.html')


def psp_message(request):
    print('a message from psp getting')

templates/market/cart.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Cart({% endblock %}
    {% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
    {% endblock %}


{% block content %}

    <div class="cart-container">
        <h2 class="cart-title">Your Cart</h2>

        <form method="post" class="cart-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-add-to-cart">Add to Cart</button>
        </form>

        <h3 class="cart-items-title">Items in Cart</h3>

        <ul class="cart-items-list">
            {% for item in cart_items %}
            <li class="cart-item">
                <span class="item-name">{{ item.product_name }}</span>
                <span class="item-price">toman{{ item.product_price }}</span>
                <span class="item-quantity">({{ item.quantity }} pcs)</span>
                <span class="item-total">Total: toman{{ item.total_price }}</span>
            </li>
            {% endfor %}
        </ul>

        <h4 class="cart-total">Total: toman{{ total_amount }}</h4>

        <a href="{% url 'market:go_gateway' %}" class="btn-checkout">Proceed to Checkout</a>
    </div>
{% endblock %}

templates/market/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
</head>
<body>

<div class="checkout-container">
    <h2 class="checkout-title">Checkout</h2>

    <h3>Your Cart</h3>
    <ul class="cart-items-list">
        {% for item in cart_items %}
            <li class="cart-item">
                <span class="item-name">{{ item.product_name }}</span>
                <span class="item-price">Price: toman{{ item.product_price }}</span>
                <span class="item-quantity">Quantity: {{ item.quantity }}</span>
                <span class="item-total">Total: toman{{ item.total_price }}</span>
            </li>
        {% endfor %}
    </ul>

    <h4 class="total-price">Total Amount: toman{{ total_price }}</h4>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn-checkout">Proceed to Payment</button>
    </form>
</div>

</body>
</html>

templates/market/failure_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>failure_page</h1>
</body>
</html>

templates/market/success_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<h1>success_page</h1>
</body>
</html>